services:
  frontend:
    build:
      context: ./frontend
    environment:
      - NODE_ENV=production
    expose:
      - "3003"

  backend:
    build:
      context: ./backend
    environment:
      - MODEL_PATH=/models/best.pt
    volumes:
      - ./backend/models:/models:ro
    expose:
      - "8000"
